import { ArrowUpRight, Network, Sparkles, Target, UsersRound } from 'lucide-react'
import Link from 'next/link'
import { PageIntro, Reveal, SectionTitle, SiteShell } from '@/components/site-shell'

const disciplines = [
  { icon: Network, eyebrow: 'Systems', title: 'Engineering & architecture', copy: 'We design resilient platforms, intelligent infrastructure, and digital systems that turn complex constraints into useful public and organizational value.' },
  { icon: Sparkles, eyebrow: 'Research', title: 'Evidence & discovery', copy: 'We investigate emerging questions across AI, geospatial science, identity, blockchain, and computational methods—then make the learning visible.' },
  { icon: Target, eyebrow: 'Impact', title: 'Technology with direction', copy: 'We keep social outcomes, the SDGs, access, and long-term community resilience in view while deciding what to build and why.' },
]

const principles = ['Curiosity before certainty', 'Evidence before noise', 'Access before exclusivity', 'Craft before shortcuts']

export default function TeamPage() {
  return <SiteShell><main className="content-page team-page">
    <PageIntro eyebrow="The people" title="Small team. Wide aperture." body="Eveth Labs Tech is a Tanzania-founded, mission-led engineering laboratory. We bring together technical practice, applied research, social purpose, and the next generation of builders." />

    <Reveal><section className="team-founder glass-card">
      <div className="team-founder-visual"><div className="team-orbit"><span /><span /><span /></div><p className="eyebrow">01 / Founder-led laboratory</p><p className="team-coordinate">06°10′S · 39°12′E<br />Zanzibar / connected globally</p></div>
      <div className="team-founder-copy"><p className="eyebrow">Founder & lead system architect</p><h2>Victor Gervas Mmanda</h2><p className="team-role">Computer scientist · Researcher · Builder</p><p className="team-body">Victor founded Eveth Labs Tech to create the kind of environment he wanted to see: a place where difficult technical work can serve real people, where research can move beyond the page, and where emerging talent can gain meaningful proximity to ambitious problems.</p><p className="team-body">His work spans enterprise systems, AI, blockchain, geospatial intelligence, computational research, and digital infrastructure. The common thread is not a single technology—it is the belief that careful engineering can widen opportunity.</p><div className="mt-7 flex flex-wrap gap-2"><span className="tag">Systems architecture</span><span className="tag">Applied AI</span><span className="tag">Computational research</span><span className="tag">Digital identity</span></div><Link href="/contact" className="inline-link">Connect with the lab <ArrowUpRight aria-hidden="true" /></Link></div>
    </section></Reveal>

    <section className="section-wrap team-section"><Reveal><SectionTitle eyebrow="How the lab thinks" title="Different disciplines. One direction." body="Eveth Labs is intentionally small and interdisciplinary. We connect perspectives that are often separated—engineering, science, design, policy, and lived experience—so better questions can become better systems." /></Reveal><div className="team-discipline-grid">{disciplines.map(({ icon: Icon, eyebrow, title, copy }) => <Reveal key={title}><article className="team-discipline glass-card"><div className="feature-icon"><Icon aria-hidden="true" /></div><p className="eyebrow">{eyebrow}</p><h3>{title}</h3><p>{copy}</p></article></Reveal>)}</div></section>

    <section className="team-manifesto section-wrap"><Reveal><div className="team-manifesto-lead"><p className="eyebrow">02 / Working principles</p><h2>Build things that leave people stronger.</h2><p>Our standard is not simply whether a system works. We ask who it reaches, what it makes possible, what evidence supports it, and whether the knowledge can travel beyond the original team.</p></div></Reveal><Reveal><div className="team-principles">{principles.map((principle, index) => <div className="team-principle" key={principle}><span>0{index + 1}</span><strong>{principle}</strong></div>)}</div></Reveal></section>

    <section className="section-wrap team-pathways"><Reveal><SectionTitle eyebrow="A growing network" title="There is more than one way to belong here." body="The team is not defined only by full-time roles. It is a growing network of collaborators, students, researchers, mentors, and builders contributing from different angles." /></Reveal><div className="team-pathway-grid"><Reveal><article className="team-pathway"><span>Collaborate</span><h3>Bring a hard problem.</h3><p>Partner with us on a platform, research question, community challenge, or technical system that deserves care.</p><Link href="/contact" className="inline-link">Start a conversation <ArrowUpRight aria-hidden="true" /></Link></article></Reveal><Reveal><article className="team-pathway"><span>Contribute</span><h3>Bring your perspective.</h3><p>We welcome emerging talent across software, science, design, research, operations, and communication.</p><Link href="/contact" className="inline-link">Introduce yourself <ArrowUpRight aria-hidden="true" /></Link></article></Reveal><Reveal><article className="team-pathway"><span>Grow</span><h3>Build visible proof.</h3><p>Real systems, documented research, and thoughtful collaboration can become a bridge to scholarships, funding, and new opportunities.</p><Link href="/projects" className="inline-link">See the work <ArrowUpRight aria-hidden="true" /></Link></article></Reveal></div></section>

    <Reveal><section className="team-closing glass-card"><div><p className="eyebrow">03 / The invitation</p><h2>Make the future more useful.</h2></div><div><p>Whether you are a potential partner, an emerging builder, a researcher, or someone with a question worth pursuing, there is room to begin.</p><Link href="/contact" className="nav-cta mt-6">Meet the lab <ArrowUpRight aria-hidden="true" /></Link></div></section></Reveal>
  </main></SiteShell>
}
