import { ArrowUpRight, BrainCircuit, Code2, Globe2, ShieldCheck, Sparkles } from 'lucide-react'
import { PageIntro, Reveal, SectionTitle, SiteShell } from '@/components/site-shell'

const pillars = [
  { icon: BrainCircuit, label: '01 / Interdisciplinary', title: 'Many disciplines. One direction.', body: 'Computer science meets computational science, engineering, geography, social inquiry, and the lived realities of the communities technology should serve.', color: 'text-cyan' },
  { icon: Sparkles, label: '02 / Mission-led', title: 'Progress that can be felt.', body: 'We align our work with social impact and the Sustainable Development Goals, focusing on useful systems that widen access and strengthen opportunity.', color: 'text-amber' },
  { icon: Code2, label: '03 / End-to-end', title: 'From question to working system.', body: 'We move between research, product thinking, architecture, implementation, and learning—without losing sight of the human outcome.', color: 'text-violet' },
  { icon: ShieldCheck, label: '04 / Responsible', title: 'Trust is part of the build.', body: 'Security, autonomy, maintainability, and honest communication are not afterthoughts. They are part of what makes technology worth keeping.', color: 'text-cyan' },
]

const principles = ['Start with the people and context', 'Make difficult knowledge useful', 'Build for dignity, access, and resilience', 'Leave systems stronger than we found them']

export default function AboutPage() {
  return <SiteShell><main className="content-page about-page">
    <PageIntro eyebrow="About the lab / Tanzania → world" title="Engineering tomorrow. Researching the future." body="Eveth Labs Tech is a mission-led engineering laboratory founded and led by Victor Gervas Mmanda. We bring technology, research, and emerging talent together to work on the challenges that matter."
    />
    <Reveal><section className="about-manifesto glass-card"><div><p className="eyebrow">Our mandate</p><h2>Build knowledge. Build capability. Build a future people can participate in.</h2></div><div className="about-manifesto-copy"><p>We exist at the intersection of thoughtful engineering and public purpose. The lab develops digital systems, conducts applied research, and creates room for young people with different perspectives to contribute to meaningful work.</p><p>Our work is grounded in Tanzania and open to the world. We believe the strongest solutions are technically rigorous, locally attentive, and generous enough to create pathways for others.</p></div></section></Reveal>
    <section className="about-pillars"><div className="about-heading"><SectionTitle eyebrow="What guides the lab" title="A wider definition of technical excellence." body="The quality of a system is measured not only by how it works, but by who it helps, what it teaches, and whether it can endure." /></div><div className="about-pillar-grid">{pillars.map(({ icon: Icon, label, title, body, color }) => <Reveal key={label}><article className="glass-card about-pillar"><Icon className={color} size={25} aria-hidden="true" /><p className="eyebrow">{label}</p><h3>{title}</h3><p>{body}</p></article></Reveal>)}</div></section>
    <section className="about-founder"><div className="about-founder-index"><p className="eyebrow">The founder</p><div className="about-founder-mark"><span>VGM</span><small>FOUNDER / BUILDER / RESEARCHER</small></div><p className="about-coordinate">06°10′S / 39°12′E<br />Zanzibar, Tanzania<br />Working across disciplines</p></div><div><p className="eyebrow">A founder-led practice</p><h2>Curiosity is the starting point. Responsibility is the measure.</h2><p className="about-founder-copy">Victor Gervas Mmanda founded Eveth Labs Tech to create a place where ambitious technical work could stay connected to people and place. His path across software, research, geospatial thinking, and digital systems shapes the lab&apos;s wide aperture.</p><p className="about-founder-copy">The lab is intentionally being built as both a working practice and a portfolio of possibility: a place to deliver useful systems, document what is learned, and help emerging talent become visible through real contribution.</p><a href="/team" className="inline-link">Meet the team <ArrowUpRight size={15} aria-hidden="true" /></a></div></section>
    <section className="about-principles"><div><p className="eyebrow">How we think</p><h2>Useful rigor over impressive complexity.</h2><p>We approach every brief as a system: understand its constraints, model its future, build its feedback loops, and leave it stronger than we found it.</p></div><div>{principles.map((principle, index) => <div className="about-principle" key={principle}><span>0{index + 1}</span><strong>{principle}</strong></div>)}</div></section>
    <section className="about-focus"><div className="about-heading"><SectionTitle eyebrow="Where the work gathers" title="Three connected fields of practice." /></div><div className="about-focus-grid"><Reveal><article><span>01</span><h3>Social infrastructure</h3><p>Digital platforms and services that improve access, participation, and institutional capacity.</p></article></Reveal><Reveal><article><span>02</span><h3>Applied research</h3><p>Evidence-led investigations that turn difficult questions into insight, prototypes, and public learning.</p></article></Reveal><Reveal><article><span>03</span><h3>Talent ecosystems</h3><p>Connections between students, builders, researchers, and organizations working toward a more capable future.</p></article></Reveal></div></section>
    <Reveal><section className="about-cta glass-card"><div><p className="eyebrow">An open invitation</p><h2>There is room here for serious questions and generous collaboration.</h2><p>Whether you are bringing a research idea, a community challenge, or an emerging talent to the table, we would like to hear from you.</p></div><a href="/contact" className="inline-link">Start a conversation <ArrowUpRight size={15} aria-hidden="true" /></a></section></Reveal>
  </main></SiteShell>
}
