import { ArrowUpRight, ExternalLink } from 'lucide-react'
import { projects } from '@/lib/site-data'
import { PageIntro, Reveal, SiteShell } from '@/components/site-shell'

export default function ProjectsPage() {
  return (
    <SiteShell>
      <main className="content-page projects-page">
        <PageIntro eyebrow="Selected work / 2022—2026" title="Systems with a reason to exist." body="A portfolio of platforms, infrastructure, research, and prototypes built from first principles—designed to expand access, strengthen institutions, and move ambitious ideas into the world." />
        <Reveal><section className="project-portfolio-intro glass-card"><div><p className="eyebrow">The portfolio lens</p><h2>Technology is most valuable when it connects people to possibility.</h2><p>Every project begins with a real constraint: a community that needs better access, an institution that needs stronger systems, or a difficult research question that deserves a rigorous answer.</p></div><div className="project-stats"><div><strong>07</strong><span>selected systems</span></div><div><strong>03</strong><span>research-led builds</span></div><div><strong>09</strong><span>SDG touchpoints</span></div></div></section></Reveal>
        <section className="project-collection"><div className="project-section-heading"><div><p className="eyebrow">01 / Selected systems</p><h2>Built for the conditions around us.</h2></div><p>From community platforms to institutional infrastructure, these projects translate technical depth into useful public and organizational value.</p></div><div className="grid gap-4 md:grid-cols-2">{projects.map((project, index) => { const href = project.externalUrl ?? `/projects/${project.slug}`; const isExternal = Boolean(project.externalUrl); return <Reveal key={project.slug}><a href={href} target={isExternal ? '_blank' : undefined} rel={isExternal ? 'noreferrer' : undefined} className={`project-card tall accent-${project.accent} ${index === 0 ? 'project-card-featured' : ''}`}><div className="flex items-center justify-between gap-4"><span className="project-type">{project.type}</span>{isExternal ? <ExternalLink size={17} className="text-muted-foreground" aria-hidden="true" /> : <ArrowUpRight size={17} className="text-muted-foreground" aria-hidden="true" />}</div><h2 className="mt-10 flex flex-wrap items-center gap-3 text-2xl font-medium tracking-tight sm:mt-12">{project.title}{project.logo ? <img src={project.logo} alt={`${project.title} logo`} className="project-logo" /> : null}</h2><p className="mt-4 max-w-lg leading-7 text-muted-foreground">{project.description}</p><div className="mt-8 flex flex-wrap gap-2">{project.tags.map((tag) => <span className="tag" key={tag}>{tag}</span>)}</div><div className="mt-8 flex items-center justify-between gap-3"><p className="text-xs uppercase tracking-[.15em] text-muted-foreground">{project.status} · {project.sdg}</p><span className="inline-flex items-center gap-2 text-sm font-medium text-primary">{isExternal ? 'Visit project' : 'Explore project'} <ArrowUpRight size={15} aria-hidden="true" /></span></div></a></Reveal>})}</div></section>
        <section className="project-practice"><div className="project-section-heading"><div><p className="eyebrow">02 / How we build</p><h2>Depth behind the interface.</h2></div><p>The visible product is only one layer. We design the architecture, feedback loops, and operational foundations that allow useful systems to last.</p></div><div className="project-practice-grid"><div><span>01</span><h3>Understand</h3><p>We map the people, context, constraints, and outcomes before choosing a technical direction.</p></div><div><span>02</span><h3>Architect</h3><p>We turn complexity into modular systems with clear boundaries, security, and room to evolve.</p></div><div><span>03</span><h3>Validate</h3><p>We test assumptions through prototypes, research, observability, and feedback from real use.</p></div></div></section>
        <Reveal><section className="project-cta glass-card"><div><p className="eyebrow">03 / Open brief</p><h2>Have a problem worth building around?</h2><p>Bring a research question, a service challenge, or an early-stage idea. We are interested in work that creates durable value for people and institutions.</p></div><a href="/contact" className="inline-link">Start a conversation <ArrowUpRight size={15} aria-hidden="true" /></a></section></Reveal>
      </main>
    </SiteShell>
  )
}
