import Link from 'next/link'
import { ArrowRight, ArrowUpRight, ChevronRight, Globe2, Layers3 } from 'lucide-react'
import { projects, research, services } from '@/lib/site-data'
import { Reveal, SectionTitle, SiteShell } from '@/components/site-shell'

const pageSummaries = [
  { eyebrow: '01 / About the lab', title: 'A mission-led engineering laboratory.', copy: 'We connect thoughtful technology, applied research, and people working toward a more inclusive future.', href: '/about', label: 'Understand our mission' },
  { eyebrow: '02 / Services', title: 'Capabilities for meaningful systems.', copy: 'Architecture, AI, infrastructure, digital products, identity research, and interdisciplinary technical inquiry.', href: '/services', label: 'Explore capabilities' },
  { eyebrow: '03 / Research', title: 'Questions worth building for.', copy: 'Evidence-led work across digital identity, geospatial intelligence, distributed systems, and social impact.', href: '/research', label: 'Explore research' },
  { eyebrow: '04 / Team', title: 'Different angles, one direction.', copy: 'A founder-led network for builders, researchers, students, and emerging technical talent.', href: '/team', label: 'Meet the people' },
]

export default function Page() { return <SiteShell><main>
  <section className="hero mx-auto max-w-7xl px-6 lg:px-8"><div className="max-w-4xl"><p className="eyebrow hero-reveal">Engineering tomorrow · researching the future</p><h1 className="display hero-reveal delay-1">Technology<br /><span className="gradient-text">with a reason.</span></h1><p className="lead hero-reveal delay-2 max-w-2xl">Eveth Labs Tech is a Tanzania-founded engineering laboratory advancing social impact, Sustainable Development Goals, applied research, and pathways for talented young people.</p><div className="hero-reveal delay-3 mt-9 flex flex-wrap gap-3"><Link href="/about" className="nav-cta">Discover the lab <ArrowUpRight size={15} /></Link><Link href="/contact" className="button-secondary">Start a conversation <ArrowRight size={15} /></Link></div></div><div className="hero-signal" aria-hidden="true"><span /><span /><span /><span /></div></section>
  <section className="section-wrap"><Reveal><SectionTitle eyebrow="The lab / in brief" title="One place for ideas, systems, and people that want to move the future forward." body="Use the paths below to explore how Eveth Labs Tech thinks, builds, researches, and grows its network." /></Reveal><div className="grid gap-4 md:grid-cols-2">{pageSummaries.map((item) => <Reveal key={item.href}><Link href={item.href} className="glass-card home-summary-card block h-full"><p className="eyebrow">{item.eyebrow}</p><h2 className="card-title">{item.title}</h2><p className="card-copy">{item.copy}</p><span className="inline-link">{item.label} <ChevronRight size={15} /></span></Link></Reveal>)}</div></section>
  <section className="section-wrap"><Reveal><SectionTitle eyebrow="Selected work" title="A snapshot of what we build." body="Explore the full portfolio for project context, technology choices, SDG alignment, and destination links." /></Reveal><div className="grid gap-4 md:grid-cols-2">{projects.slice(0,4).map((project) => <Reveal key={project.slug}><Link href={project.externalUrl ?? `/projects/${project.slug}`} target={project.externalUrl ? '_blank' : undefined} rel={project.externalUrl ? 'noreferrer' : undefined} className={`project-card accent-${project.accent}`}><div className="flex items-start justify-between gap-4"><span className="project-type">{project.type}</span><ArrowUpRight size={17} className="text-muted-foreground" /></div><h3 className="mt-12 flex items-center gap-3 text-xl font-medium tracking-tight">{project.title}{project.logo ? <img src={project.logo} alt={`${project.title} logo`} className="project-logo" /> : null}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{project.description}</p><p className="mt-7 text-xs uppercase tracking-[.15em] text-muted-foreground">{project.status} · {project.sdg}</p></Link></Reveal>)}</div><Link href="/projects" className="inline-link mt-8">View all projects <ArrowRight size={15} /></Link></section>
  <section className="section-wrap grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><Reveal><SectionTitle eyebrow="Research frontier" title="Questions worth building for." body="We contribute to knowledge at the convergence of AI, distributed systems, computational science, and real-world impact." /><Link href="/research" className="inline-link">Explore all research <ArrowRight size={15} /></Link></Reveal><div>{research.slice(0,3).map(([status,title,copy],i) => <Reveal key={title}><div className="research-row"><span className={`status-dot status-${i}`} /><div><span className="eyebrow !text-[10px]">{status}</span><h3 className="mt-2 font-medium">{title}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{copy}</p></div></div></Reveal>)}</div></section>
  <section className="section-wrap"><div className="cta-panel"><div><p className="eyebrow">Open invitation</p><h2 className="section-title mt-3 max-w-xl">Bring a question, an idea, or an angle.</h2><p className="mt-4 max-w-lg leading-7 text-muted-foreground">Whether you want to collaborate, contribute, research, or learn, there is a place to begin.</p></div><Link href="/contact" className="nav-cta shrink-0">Connect with the lab <ArrowUpRight size={15} /></Link></div></section>
</main></SiteShell> }
