import Link from 'next/link'
import { ArrowRight, ArrowUpRight, BrainCircuit, ChevronRight, Code2, Globe2, Layers3, ShieldCheck } from 'lucide-react'
import { projects, research, services, process } from '@/lib/site-data'
import { Reveal, SectionTitle, SiteShell } from '@/components/site-shell'

export default function Page() { return <SiteShell><main>
  <section className="hero mx-auto max-w-7xl px-6 lg:px-8"><div className="max-w-4xl"><p className="eyebrow hero-reveal">Self-hosted remote engineering laboratory</p><h1 className="display hero-reveal delay-1">Transforming ideas<br /><span className="gradient-text">into digital reality.</span></h1><p className="lead hero-reveal delay-2 max-w-2xl">From systems architecture to advanced computational research, we build intelligent production systems for technology, science, and society.</p><div className="hero-reveal delay-3 mt-9 flex flex-wrap gap-3"><Link href="/projects" className="nav-cta">Explore our work <ArrowUpRight size={15} /></Link><Link href="/contact" className="button-secondary">Start a conversation <ArrowRight size={15} /></Link></div></div><div className="hero-signal" aria-hidden="true"><span /><span /><span /><span /></div></section>
  <section className="section-wrap"><Reveal><SectionTitle eyebrow="The lab" title="Engineering with a wider field of view." body="Eveth Labs Tech is a center of excellence for computational science and interdisciplinary problem-solving. We architect complete digital ecosystems—not just isolated features." /></Reveal><div className="grid gap-4 md:grid-cols-3"><Reveal className="md:col-span-2"><div className="glass-card h-full"><div className="feature-icon"><Layers3 size={20} /></div><h3 className="card-title">Complexity, made useful.</h3><p className="card-copy">Mathematics and physics meet software engineering, artificial intelligence, distributed systems, and DevOps. Every system is designed to be secure, maintainable, and ready to grow.</p><Link href="/about" className="inline-link">How we think <ChevronRight size={15} /></Link></div></Reveal><Reveal><div className="glass-card h-full"><div className="feature-icon violet"><Globe2 size={20} /></div><p className="metric">01<span>lab</span></p><p className="card-copy">Based in Dar es Salaam.<br />Available anywhere.</p></div></Reveal></div></section>
  <section className="section-wrap"><Reveal><SectionTitle eyebrow="Capabilities" title="From first principles to production." body="A focused set of capabilities for building things that matter." /></Reveal><div className="grid gap-x-8 gap-y-0 md:grid-cols-2 lg:grid-cols-3">{services.map(([num,title,copy]) => <Reveal key={num}><div className="service-row"><span className="service-number">{num}</span><div><h3 className="font-medium">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{copy}</p></div></div></Reveal>)}</div></section>
  <section className="section-wrap"><Reveal><SectionTitle eyebrow="Selected work" title="Production-ready systems, research-backed." /></Reveal><div className="grid gap-4 md:grid-cols-2">{projects.slice(0,4).map((project) => <Reveal key={project.slug}><Link href={`/projects/${project.slug}`} className={`project-card accent-${project.accent}`}><div className="flex items-start justify-between gap-4"><span className="project-type">{project.type}</span><ArrowUpRight size={17} className="text-muted-foreground" /></div><h3 className="mt-12 text-xl font-medium tracking-tight">{project.title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{project.description}</p><div className="mt-7 flex flex-wrap gap-2">{project.tags.map(tag => <span key={tag} className="tag">{tag}</span>)}</div></Link></Reveal>)}</div><Link href="/projects" className="inline-link mt-8">View all projects <ArrowRight size={15} /></Link></section>
  <section className="section-wrap grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><Reveal><SectionTitle eyebrow="Research frontier" title="Questions worth building for." body="We contribute to the global body of knowledge at the convergence of AI, distributed systems, computational science, and real-world impact." /><Link href="/research" className="inline-link">Explore research <ArrowRight size={15} /></Link></Reveal><div>{research.slice(0,4).map(([status,title,copy],i) => <Reveal key={title}><div className="research-row"><span className={`status-dot status-${i}`} /><div><div className="flex items-center gap-3"><span className="eyebrow !text-[10px]">{status}</span></div><h3 className="mt-2 font-medium">{title}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{copy}</p></div></div></Reveal>)}</div></section>
  <section className="section-wrap"><div className="cta-panel"><div><p className="eyebrow">Build with us</p><h2 className="section-title mt-3 max-w-xl">The future is a systems problem.</h2><p className="mt-4 max-w-lg leading-7 text-muted-foreground">Bring us the hard question. We&apos;ll bring a clear architecture, thoughtful engineering, and a path to impact.</p></div><Link href="/contact" className="nav-cta shrink-0">Let&apos;s talk <ArrowUpRight size={15} /></Link></div></section>
</main></SiteShell> }
