import { ArrowUpRight, BookOpen, FlaskConical, Globe2, Layers3, Network, Sparkles } from 'lucide-react'
import { research } from '@/lib/site-data'
import { PageIntro, Reveal, SiteShell } from '@/components/site-shell'

const focusAreas = [
  { icon: Network, label: 'Digital systems', title: 'Infrastructure for participation', copy: 'We study identity, payments, platforms, and distributed systems that help people and institutions participate with more trust and agency.' },
  { icon: Globe2, label: 'Planetary intelligence', title: 'Evidence from the Earth', copy: 'Remote sensing, geospatial analysis, and environmental data help us understand changing ecosystems and support better decisions.' },
  { icon: Sparkles, label: 'Emerging intelligence', title: 'AI under real constraints', copy: 'Our applied AI work asks how models can become useful, explainable, and responsible beyond ideal laboratory conditions.' },
]
const method = [['01', 'Frame', 'Start with a meaningful question, its context, and the people affected by the answer.'], ['02', 'Investigate', 'Combine literature, field context, data, and technical experimentation to test what holds.'], ['03', 'Translate', 'Turn findings into a paper, prototype, policy insight, or open conversation that others can use.']]

export default function ResearchPage() { return <SiteShell><main className="content-page research-page">
  <PageIntro eyebrow="Research & insights" title="Engineering tomorrow. Researching the future." body="Eveth Labs Tech is a mission-led research and engineering laboratory. We explore difficult questions at the intersection of technology, society, environment, and opportunity—then make the work useful beyond the page." />
  <section className="research-hero-panel glass-card"><div><p className="eyebrow">Research mandate / 001</p><h2>Evidence before noise.</h2><p>Our research is grounded in the realities of Tanzania and connected to global questions. We care about work that is rigorous enough to trust, practical enough to apply, and open enough to move a field forward.</p></div><div className="research-signal"><FlaskConical aria-hidden="true" /><span>APPLIED / INTERDISCIPLINARY / PUBLIC VALUE</span></div></section>
  <section className="research-section"><Reveal><div className="research-section-heading"><div><p className="eyebrow">Areas of inquiry</p><h2>Questions worth carrying.</h2></div><p>We connect computational methods with the human and environmental systems they are meant to serve.</p></div></Reveal><div className="research-focus-grid">{focusAreas.map(({icon: Icon,label,title,copy}) => <Reveal key={title}><article className="research-focus glass-card"><Icon aria-hidden="true" /><p className="eyebrow">{label}</p><h3>{title}</h3><p>{copy}</p></article></Reveal>)}</div></section>
  <section className="research-section"><Reveal><div className="research-section-heading"><div><p className="eyebrow">Selected portfolio</p><h2>From investigation to contribution.</h2></div><p>Projects move at different speeds. Each entry is labeled honestly, with a clear path to the source where one exists.</p></div></Reveal><div className="research-list">{research.map(([status,title,copy,url,linkLabel],i) => <Reveal key={title}><article className="research-row large"><span className={`status-dot status-${i}`} /><div className="min-w-0"><div className="research-row-meta"><p className="eyebrow !text-[10px]">{status}</p><span>0{i+1}</span></div><h3>{title}</h3><p>{copy}</p>{title === 'Earth Observation & Geospatial Analytics' && <p className="research-attribution">This work was not conducted by Eveth Labs Tech. It was a student participation by founder Victor Gervas Mmanda during his studies at SUZA.</p>}{url && <a href={url} target="_blank" rel="noreferrer" className="inline-link">{linkLabel}<ArrowUpRight aria-hidden="true" /></a>}</div></article></Reveal>)}</div></section>
  <section className="research-section research-method"><Reveal><div className="research-section-heading"><div><p className="eyebrow">How we work</p><h2>A clear route from curiosity to use.</h2></div><p>Research becomes more valuable when the method is visible. We make room for uncertainty while keeping the next step concrete.</p></div></Reveal><div className="research-method-grid">{method.map(([number,title,copy]) => <Reveal key={number}><article><span>{number}</span><Layers3 aria-hidden="true" /><h3>{title}</h3><p>{copy}</p></article></Reveal>)}</div></section>
  <section className="research-cta glass-card"><div><BookOpen aria-hidden="true" /><p className="eyebrow">Open research desk</p><h2>Have a question the lab should investigate?</h2><p>We welcome collaborators, students, institutions, and funders who want to turn a meaningful question into evidence and action.</p></div><a href="/contact" className="inline-link">Start a conversation <ArrowUpRight aria-hidden="true" /></a></section>
</main></SiteShell> }
